// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_kF5J3FKpwh0ufu7TKPv3jr02Rw6crY',
    appId: '1:363105319244:web:f72ef7b86f23083131b7e9',
    messagingSenderId: '363105319244',
    projectId: 'social-media-app-47ca1',
    authDomain: 'social-media-app-47ca1.firebaseapp.com',
    storageBucket: 'social-media-app-47ca1.firebasestorage.app',
    measurementId: 'G-SZZZ342G2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrD67SjTmYMwHqYj3td9Dr8j_-6FHoNo',
    appId: '1:363105319244:android:01d117fa33b52e0c31b7e9',
    messagingSenderId: '363105319244',
    projectId: 'social-media-app-47ca1',
    storageBucket: 'social-media-app-47ca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAhpMG28UVyDYEIDtRRmAqqXCr6Sa28cU',
    appId: '1:363105319244:ios:68b8671e4f0dd9ba31b7e9',
    messagingSenderId: '363105319244',
    projectId: 'social-media-app-47ca1',
    storageBucket: 'social-media-app-47ca1.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAhpMG28UVyDYEIDtRRmAqqXCr6Sa28cU',
    appId: '1:363105319244:ios:68b8671e4f0dd9ba31b7e9',
    messagingSenderId: '363105319244',
    projectId: 'social-media-app-47ca1',
    storageBucket: 'social-media-app-47ca1.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_kF5J3FKpwh0ufu7TKPv3jr02Rw6crY',
    appId: '1:363105319244:web:a7a2f04d0fa0fa5d31b7e9',
    messagingSenderId: '363105319244',
    projectId: 'social-media-app-47ca1',
    authDomain: 'social-media-app-47ca1.firebaseapp.com',
    storageBucket: 'social-media-app-47ca1.firebasestorage.app',
    measurementId: 'G-L8XLYFXQFB',
  );

}